
import { ColorSchemeOption, LayoutOption, ColorScheme, Product, TypographyOption } from './types';
import type { TFunction } from './App';

export const COLOR_SCHEMES: Record<ColorSchemeOption, ColorScheme> = {
  [ColorSchemeOption.PlatinumCharcoal]: {
    light: {
      primary: '#8D99AE',
      secondary: '#2B2D42',
      background: '#EDF2F4',
      textPrimary: '#2B2D42',
      textSecondary: '#4A4E69',
      success: '#4CAF50',
    },
    dark: {
      primary: '#8D99AE',
      secondary: '#EDF2F4',
      background: '#2B2D42',
      textPrimary: '#EDF2F4',
      textSecondary: '#A0AEC0',
      success: '#4CAF50',
    },
    defaultMode: 'light',
  },
  [ColorSchemeOption.EmeraldGold]: {
    light: {
      primary: '#386641',
      secondary: '#B8860B',
      background: '#FDF8E7',
      textPrimary: '#283618',
      textSecondary: '#6A775C',
      success: '#B8860B',
    },
    dark: {
      primary: '#6A994E',
      secondary: '#F2E8C6',
      background: '#283618',
      textPrimary: '#FDF8E7',
      textSecondary: '#A9B3A1',
      success: '#B8860B',
    },
    defaultMode: 'light',
  },
  [ColorSchemeOption.SapphireSilver]: {
    light: {
      primary: '#0077B6',
      secondary: '#A9B2C3',
      background: '#FFFFFF',
      textPrimary: '#1A202C',
      textSecondary: '#4A5568',
      success: '#00B4D8',
    },
    dark: {
      primary: '#00B4D8',
      secondary: '#A9B2C3',
      background: '#1A202C',
      textPrimary: '#FFFFFF',
      textSecondary: '#CBD5E0',
      success: '#00B4D8',
    },
    defaultMode: 'light',
  },
  [ColorSchemeOption.UniversalSerenity]: {
    light: {
      primary: '#6A8D9B',
      secondary: '#F7E7CE',
      background: '#F5F5F5',
      textPrimary: '#36454F',
      textSecondary: '#55626d',
      success: '#5cb85c',
    },
    dark: {
      primary: '#6A8D9B',
      secondary: '#8E8270',
      background: '#36454F',
      textPrimary: '#F5F5F5',
      textSecondary: '#B0B6BA',
      success: '#5cb85c',
    },
    defaultMode: 'light',
  },
  [ColorSchemeOption.NaturalElegance]: {
    light: {
      primary: '#C97B63',
      secondary: '#E0A458',
      background: '#FAF6EE',
      textPrimary: '#4F553A',
      textSecondary: '#71775f',
      success: '#6A775C',
    },
    dark: {
      primary: '#C97B63',
      secondary: '#E0A458',
      background: '#4F553A',
      textPrimary: '#FAF6EE',
      textSecondary: '#BFC3B4',
      success: '#6A775C',
    },
    defaultMode: 'light',
  },
  [ColorSchemeOption.ModernMinimalism]: {
    light: {
      primary: '#0A694D',
      secondary: '#4A5568',
      background: '#FFFFFF',
      textPrimary: '#1A202C',
      textSecondary: '#4A5568',
      success: '#0A694D',
    },
    dark: {
      primary: '#0A694D',
      secondary: '#A8A8A8',
      background: '#121212',
      textPrimary: '#EAEAEA',
      textSecondary: '#A8A8A8',
      success: '#0A694D',
    },
    defaultMode: 'dark',
  },
  [ColorSchemeOption.MidnightGold]: {
    light: {
        primary: '#C79900',
        secondary: '#1A202C',
        background: '#F7FAFC',
        textPrimary: '#1A202C',
        textSecondary: '#4A5568',
        success: '#D4AF37',
    },
    dark: {
      primary: '#D4AF37',
      secondary: '#E5C163',
      background: '#1A202C',
      textPrimary: '#F7FAFC',
      textSecondary: '#A0AEC0',
      success: '#D4AF37',
    },
    defaultMode: 'dark',
  },
  [ColorSchemeOption.IvoryTaupe]: {
    light: {
      primary: '#5D5C61',
      secondary: '#737277',
      background: '#F4F1EA',
      textPrimary: '#373737',
      textSecondary: '#737277',
      success: '#8D8C91',
    },
    dark: {
      primary: '#B7B5B9',
      secondary: '#F4F1EA',
      background: '#373737',
      textPrimary: '#F4F1EA',
      textSecondary: '#A1A0A4',
      success: '#8D8C91',
    },
    defaultMode: 'light',
  },
  [ColorSchemeOption.DeepSea]: {
    light: {
        primary: '#415A77',
        secondary: '#778DA9',
        background: '#E0E1DD',
        textPrimary: '#0D1B2A',
        textSecondary: '#415A77',
        success: '#415A77',
    },
    dark: {
      primary: '#415A77',
      secondary: '#778DA9',
      background: '#0D1B2A',
      textPrimary: '#E0E1DD',
      textSecondary: '#778DA9',
      success: '#415A77',
    },
    defaultMode: 'dark',
  },
  [ColorSchemeOption.BlackGold]: {
    light: {
        primary: '#C79900',
        secondary: '#14213D',
        background: '#FFFFFF',
        textPrimary: '#1A202C',
        textSecondary: '#4A5568',
        success: '#C79900'
    },
    dark: {
      primary: '#C79900',
      secondary: '#14213D',
      background: '#1A202C',
      textPrimary: '#E5E5E5',
      textSecondary: '#A9A9A9',
      success: '#C79900',
    },
    defaultMode: 'dark',
  },
   [ColorSchemeOption.ModernSleek]: {
    light: {
      primary: '#007AFF',
      secondary: '#E5E5EA',
      background: '#FFFFFF',
      textPrimary: '#1D1D1F',
      textSecondary: '#86868B',
      success: '#34C759',
    },
    dark: {
      primary: '#0A84FF',
      secondary: '#3A3A3C',
      background: '#000000',
      textPrimary: '#F5F5F7',
      textSecondary: '#8E8E93',
      success: '#30D158',
    },
    defaultMode: 'light',
  },
};

export const LAYOUT_OPTIONS = [
  { id: LayoutOption.Minimalist, label: 'Modern Minimalist' },
  { id: LayoutOption.Classic, label: 'Classic Luxury' },
  { id: LayoutOption.Artistic, label: 'Contemporary Chic' },
  { id: LayoutOption.MonochromaticGallery, label: 'Monochromatic Gallery' },
  { id: LayoutOption.ArchitecturalBold, label: 'Architectural Bold' },
  { id: LayoutOption.ModernSleek, label: 'Modern Sleek' },
];

export const COLOR_SCHEME_OPTIONS = [
  { id: ColorSchemeOption.PlatinumCharcoal, label: 'Platinum & Charcoal' },
  { id: ColorSchemeOption.EmeraldGold, label: 'Emerald & Gold' },
  { id: ColorSchemeOption.SapphireSilver, label: 'Sapphire & Silver' },
  { id: ColorSchemeOption.UniversalSerenity, label: 'Universal Serenity' },
  { id: ColorSchemeOption.NaturalElegance, label: 'Natural Elegance' },
  { id: ColorSchemeOption.ModernMinimalism, label: 'Modern Minimalism' },
  { id: ColorSchemeOption.MidnightGold, label: 'Midnight Gold' },
  { id: ColorSchemeOption.IvoryTaupe, label: 'Ivory & Taupe' },
  { id: ColorSchemeOption.DeepSea, label: 'Deep Sea' },
  { id: ColorSchemeOption.BlackGold, label: 'Black & Gold' },
  { id: ColorSchemeOption.ModernSleek, label: 'Modern Sleek' },
];

export const TYPOGRAPHY_OPTIONS = [
  { id: TypographyOption.Modern, label: 'Modern (Serif Headings)' },
  { id: TypographyOption.Classic, label: 'Classic (Full Serif)' },
  { id: TypographyOption.Contemporary, label: 'Contemporary (Sans-Serif)' },
  { id: TypographyOption.LuxeModern, label: 'Luxe Modern (Mixed)' },
  { id: TypographyOption.RefinedSerif, label: 'Refined Serif (Full Serif)' },
  { id: TypographyOption.ModernSleek, label: 'Modern Sleek (Sans-Serif)' },
];

export const PRODUCTS: Product[] = [
  { id: 1, nameKey: 'product_sofa_name', categoryKey: 'product_sofa_category', imageUrl: 'https://picsum.photos/seed/sofa/800/600' },
  { id: 2, nameKey: 'product_chair_name', categoryKey: 'product_chair_category', imageUrl: 'https://picsum.photos/seed/chair/800/600' },
  { id: 3, nameKey: 'product_table_name', categoryKey: 'product_table_category', imageUrl: 'https://picsum.photos/seed/table/800/600' },
  { id: 4, nameKey: 'product_lamp_name', categoryKey: 'product_lamp_category', imageUrl: 'https://picsum.photos/seed/lamp/800/600' },
  { id: 5, nameKey: 'product_bed_name', categoryKey: 'product_bed_category', imageUrl: 'https://picsum.photos/seed/bed/800/600' },
  { id: 6, nameKey: 'product_cabinet_name', categoryKey: 'product_cabinet_category', imageUrl: 'https://picsum.photos/seed/cabinet/800/600' },
];

export const getTextContent = (t: TFunction) => ({
  hero: {
    minimalist: {
      title: t('hero_minimalist_title'),
      subtitle: t('hero_minimalist_subtitle'),
      cta: t('hero_cta_explore')
    },
    classic: {
      title: t('hero_classic_title'),
      subtitle: t('hero_classic_subtitle'),
      cta: t('hero_cta_discover')
    },
    artistic: {
      title: t('hero_artistic_title'),
      subtitle: t('hero_artistic_subtitle'),
      cta: t('hero_cta_experience')
    },
    'monochromatic-gallery': {
      title: t('hero_gallery_title'),
      subtitle: t('hero_gallery_subtitle'),
      cta: t('hero_cta_explore')
    },
    'architectural-bold': {
      title: t('hero_architectural_title'),
      subtitle: t('hero_architectural_subtitle'),
      cta: t('hero_cta_discover')
    },
    'modern-sleek': {
      title: t('hero_sleek_title'),
      subtitle: t('hero_sleek_subtitle'),
      cta: t('hero_cta_learn_more')
    }
  },
  products: {
    title: t('products_title'),
    subtitle: t('products_subtitle'),
    cta: t('products_cta')
  },
  about: {
    title: t('about_title'),
    p1: t('about_p1'),
    p2: t('about_p2'),
  },
});


export const TEXTS: Record<string, Record<string, string>> = {
  en: {
    logo: 'Awlad Raafat',
    nav_home: 'Home',
    nav_shop: 'Shop',
    nav_about: 'About',
    nav_locations: 'Locations',
    nav_contact: 'Contact',
    lang_toggle_en: 'English',
    lang_toggle_ar: 'العربية',
    hero_minimalist_title: 'Design That Breathes',
    hero_minimalist_subtitle: 'Discover harmony in form and function. Uncompromising quality for the modern home.',
    hero_classic_title: 'A Legacy of Luxury',
    hero_classic_subtitle: 'Experience timeless elegance, crafted with passion and heritage for generations.',
    hero_artistic_title: 'Where Art Meets Furniture',
    hero_artistic_subtitle: 'Bold designs that transform spaces and inspire conversation. Live your masterpiece.',
    hero_gallery_title: 'The Art of Simplicity',
    hero_gallery_subtitle: 'Curated forms, refined materials. A new perspective on luxury living.',
    hero_architectural_title: 'Structured Elegance',
    hero_architectural_subtitle: 'Bold lines and confident forms that define space with intention and grace.',
    hero_sleek_title: 'The Future of Design',
    hero_sleek_subtitle: 'Engineered for simplicity. Crafted for life.',
    hero_cta_explore: 'Explore Collections',
    hero_cta_discover: 'Discover Our Heritage',
    hero_cta_experience: 'Experience the Art',
    hero_cta_learn_more: 'Learn More',
    products_title: 'Featured Collections',
    products_subtitle: 'Hand-selected pieces that define elegance and comfort.',
    products_cta: 'View Details',
    about_title: 'Our Story: The Art of Egyptian Craftsmanship',
    about_p1: 'Founded in the heart of Egypt, Awlad Raafat began with a simple vision: to blend ancestral woodworking techniques with contemporary design. For over fifty years, our family has been dedicated to creating furniture that is not just an object, but a piece of heritage.',
    about_p2: 'Today, we bring this legacy to the world, with showrooms in Cairo, Alexandria, and now serving our discerning clients in the United States. Each piece tells a story of meticulous craftsmanship and a commitment to unparalleled quality.',
    footer_contact_header: 'Contact Us',
    footer_egypt_office: 'Egypt Office',
    footer_us_office: 'USA Office',
    footer_quick_links: 'Quick Links',
    footer_privacy: 'Privacy Policy',
    footer_terms: 'Terms of Service',
    footer_social_header: 'Follow Us',
    footer_copyright: '© 2024 Awlad Raafat. All Rights Reserved.',
    product_sofa_name: 'The Nile Sofa',
    product_sofa_category: 'Living Room',
    product_chair_name: 'Pharaoh Armchair',
    product_chair_category: 'Seating',
    product_table_name: 'Luxor Dining Table',
    product_table_category: 'Dining',
    product_lamp_name: 'Giza Floor Lamp',
    product_lamp_category: 'Lighting',
    product_bed_name: 'Cleopatra Bed',
    product_bed_category: 'Bedroom',
    product_cabinet_name: 'Alexandria Cabinet',
    product_cabinet_category: 'Storage',
  },
  ar: {
    logo: 'أولاد رأفت',
    nav_home: 'الرئيسية',
    nav_shop: 'المجموعات',
    nav_about: 'قصتنا',
    nav_locations: 'فروعنا',
    nav_contact: 'اتصل بنا',
    lang_toggle_en: 'English',
    lang_toggle_ar: 'العربية',
    hero_minimalist_title: 'تصميم يتنفس بالحياة',
    hero_minimalist_subtitle: 'اكتشفوا التناغم المثالي بين الشكل والوظيفة. جودة لا تضاهى لمنزلكم العصري.',
    hero_classic_title: 'إرث من الفخامة',
    hero_classic_subtitle: 'عِيشوا تجربة الأناقة الخالدة، المصنوعة بشغف وإرث عريق تتوارثه الأجيال.',
    hero_artistic_title: 'حيث يرتقي الأثاث إلى الفن',
    hero_artistic_subtitle: 'تصاميم جريئة تعيد تعريف المساحات وتلهم الحوار. اقتنوا تحفتكم الفنية التي تعبر عنكم.',
    hero_gallery_title: 'جوهر البساطة الأنيقة',
    hero_gallery_subtitle: 'أشكال منتقاة، مواد مصقولة. منظور جديد للمعيشة الفاخرة.',
    hero_architectural_title: 'أناقة هيكلية',
    hero_architectural_subtitle: 'خطوط جريئة وأشكال واثقة تحدد المساحة بقوة ورشاقة.',
    hero_sleek_title: 'مستقبل التصميم',
    hero_sleek_subtitle: 'مصممة للبساطة. مصنوعة للحياة.',
    hero_cta_explore: 'اكتشفوا المجموعات',
    hero_cta_discover: 'اكتشفوا تراثنا',
    hero_cta_experience: 'عيشوا التجربة الفنية',
    hero_cta_learn_more: 'اعرف المزيد',
    products_title: 'مجموعاتنا المميزة',
    products_subtitle: 'قطعٌ فنية مختارة بعناية لتعيد تعريف الأناقة والراحة في مساحاتكم.',
    products_cta: 'اكتشفوا المزيد',
    about_title: 'قصتنا: فن الحرفية المصرية الأصيلة',
    about_p1: 'تجسيداً لرؤية تمزج بين أصالة حرفة النجارة المصرية وتطلعات التصميم المعاصر، انطلقت مسيرة "أولاد رأفت" من قلب مصر. على مدى أكثر من خمسة عقود، كرست عائلتنا شغفها وجهدها لإبداع قطع أثاث تتجاوز مفهومها المادي، لتصبح إرثاً فنياً بحد ذاته.',
    about_p2: 'واليوم، نحمل هذا الإرث العريق بفخر إلى العالم، عبر معارضنا في القاهرة والإسكندرية، ونقدمه لعملائنا المميزين في الولايات المتحدة. كل قطعة بين أيديكم هي حكاية تُروى فصولها بالحرفية المتقنة والالتزام المطلق بأرقى معايير الجودة.',
    footer_contact_header: 'تواصلوا معنا',
    footer_egypt_office: 'مكتب مصر',
    footer_us_office: 'مكتب الولايات المتحدة',
    footer_quick_links: 'روابط سريعة',
    footer_privacy: 'سياسة الخصوصية',
    footer_terms: 'شروط الخدمة',
    footer_social_header: 'تابعونا',
    footer_copyright: '© 2024 أولاد رأفت. جميع الحقوق محفوظة.',
    product_sofa_name: 'أريكة النيل',
    product_sofa_category: 'غرفة المعيشة',
    product_chair_name: 'مقعد فرعون',
    product_chair_category: 'مقاعد',
    product_table_name: 'طاولة طعام الأقصر',
    product_table_category: 'غرفة الطعام',
    product_lamp_name: 'مصباح الجيزة الأرضي',
    product_lamp_category: 'إضاءة',
    product_bed_name: 'سرير كليوباترا',
    product_bed_category: 'غرفة النوم',
    product_cabinet_name: 'خزانة الإسكندرية',
    product_cabinet_category: 'تخزين',
  }
};